### ISSUE TITLE
Destination directory /etc/monit/conf.d does not exist" when monit_setup_mode is False

### ISSUE THREAD

**Issue by ukanga** [onaio/ansible-monit#1]

**Comment by ukanga** [comment]
I suspect that it has to do with the tasks [Copy monit config files](https://github.com/onaio/ansible-monit/blob/master/tasks/main.yml#L5) and  [Copy monit template config files](https://github.com/onaio/ansible-monit/blob/master/tasks/main.yml#L14) not having the same check, ` when: monit_setup_mode` as the [`include: setup.yml`](https://github.com/onaio/ansible-monit/blob/master/tasks/main.yml#L2) task. This happens on a new server setup where monit has not been installed before.

Is there an issue if we add the same condition for this other tasks?

**Comment by jasonrogena** [comment]
Cool. The assumption this role makes is that it had already been run in setup mode, before running in app mode
